### ISSUE TITLE
error importing launchpad branch

### ISSUE THREAD

**Issue by jdfrankland** [felipec/git-remote-bzr#11]
hi
i have used git-remote-bzr successfully to import a few branches of my project from launchpad/bzr to git, however with this particular branch i have a problem:

    % git remote add kalivedadoc bzr::lp:kaliveda/kalivedadoc
    % git fetch kalivedadoc
    progress revision 100 'master' (100/944)
    progress revision 200 'master' (200/944)
    progress revision 300 'master' (300/944)
    progress revision 400 'master' (400/944)
    progress revision 500 'master' (500/944)
    progress revision 600 'master' (600/944)
    progress revision 700 'master' (700/944)
    progress revision 800 'master' (800/944)
    progress revision 900 'master' (900/944)
    fatal: Empty path component found in input
    fast-import: dumping crash report to .git/fast_import_crash_16343
    fatal: Error while running fast-import
    % Traceback (most recent call last):
      File "/usr/bin/git-remote-bzr", line 1022, in <module>
        sys.exit(main(sys.argv))
      File "/usr/bin/git-remote-bzr", line 1006, in main
        do_import(parser)
      File "/usr/bin/git-remote-bzr", line 437, in do_import
        export_branch(repo, name)
      File "/usr/bin/git-remote-bzr", line 359, in export_branch
        modified_final = export_files(cur_tree, modified)
      File "/usr/bin/git-remote-bzr", line 277, in export_files
        print d
    IOError: [Errno 32] Broken pipe

I assume there is something nasty in the bzr branch which git-remote-bzr can't handle?
Thanks for any help

**Comment by felipec** [comment]
Anything interesting in the crash report?

**Comment by felipec** [comment]
I tried and I got this:

> * M 100644 :1386 /examples/SelMult.cpp

Seems like there's something wrong with that file (it starts at root).
