### ISSUE TITLE
No instruction about the following error: Could not determine revno for {x} because its ancestry shows a ghost at {y}

### ISSUE THREAD

**Issue by mttrs** [felipec/git-remote-bzr#14]
- What  
There is no instruction about the following error: Could not determine revno for {xx} because its ancestry shows a ghost at {y}

Could anyone please tell me what I should do next when I got the error? I have no idea...

```bash
# Bazaar 2.6.0dev2
# git version 2.4.1

% git clone "bzr://xxx/trunk"

Clonage dans 'trunk'...
Traceback (most recent call last):
  File "/usr/local/bin/git-remote-bzr", line 1022, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/git-remote-bzr", line 1004, in main
    do_list(parser)
  File "/usr/local/bin/git-remote-bzr", line 804, in do_list
    branch.revision_id_to_dotted_revno(revid)
  File "<string>", line 4, in revision_id_to_dotted_revno_read_locked
  File "/usr/lib/python2.7/dist-packages/bzrlib/branch.py", line 399, in revision_id_to_dotted_revno
    return self._do_revision_id_to_dotted_revno(revision_id)
  File "/usr/lib/python2.7/dist-packages/bzrlib/branch.py", line 413, in _do_revision_id_to_dotted_revno
    revno = self.revision_id_to_revno(revision_id)
  File "<string>", line 4, in revision_id_to_revno_read_locked
  File "/usr/lib/python2.7/dist-packages/bzrlib/branch.py", line 3013, in revision_id_to_revno
    raise errors.GhostRevisionsHaveNoRevno(revision_id, e.revision_id)
bzrlib.errors.GhostRevisionsHaveNoRevno: Could not determine revno for {personA@example.com-20xx-xxx} because its ancestry shows a ghost at {personB@example.com-yyy}
```

**Comment by mttrs** [comment]
Could anyone tell me a work-around?

**Comment by felipec** [comment]
Not exactly sure. Do you know how to create a ghost revision?

**Comment by mttrs** [comment]
I have no idea... I resolved the issue with my script, so I'd like to close this issue.
Thanks!
