### ISSUE TITLE
Cloning a local Bazaar repo fails: "This version of fast-import does not support feature done"

### ISSUE THREAD

**Issue by bugmenot2** [felipec/git-remote-bzr#19]
```
Z:\>git version --build-options
git version 2.10.1.windows.1
sizeof-long: 4
machine: x86_64

Z:\>python --version
Python 2.7.12

Z:\>git clone -v "bzr::file:///Z:/Bazaar/" Bzr2Git
Cloning into 'Bzr2Git'...
.atal: This version of fast-import does not support feature done
fast-import: dumping crash report to Z:/Bzr2Git/.git/fast_import_crash_2264
fatal: Error while running fast-import

Z:\>Traceback (most recent call last):
  File "Z:\git-remote-bzr", line 1022, in <module>
    sys.exit(main(sys.argv))
  File "Z:\git-remote-bzr", line 1006, in main
    do_import(parser)
  File "Z:\git-remote-bzr", line 437, in do_import
    export_branch(repo, name)
  File "Z:\git-remote-bzr", line 359, in export_branch
    modified_final = export_files(cur_tree, modified)
  File "Z:\git-remote-bzr", line 277, in export_files
    print d
IOError: [Errno 22] Invalid argument
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
```
    fast-import crash report:
        fast-import process: 2264
        parent process     : 1
        at 2016-10-17 10:24:47 +0000
    
    fatal: This version of fast-import does not support feature done
    .
    
    Most Recent Commands Before Crash
    ---------------------------------
    * feature done
    
    Active Branch LRU
    -----------------
        active_branches = 0 cur, 5 max
    
      pos  clock name
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
    Inactive Branches
    -----------------
    
    Marks
    -----
    
    -------------------
    END OF CRASH REPORT

**Comment by felipec** [comment]
Is this still an issue?
